In [51]:
import numpy as np
import pandas as pd
from scipy import stats
from numpy import random

In [ ]:
for i in range(30):
    veri = random.normal(loc=0, scale=1)
    print(veri)

In [162]:
## ortalaması 0, standart sapması 1 olan 30 adet veri ürettik
veri = random.normal(loc=0, scale=1, size=30)
veri

array([ 0.22693227,  0.17409872,  0.32761306,  1.17860006,  1.18050938,
        1.53244615,  0.28843244, -1.76247762, -1.36962976, -0.78442794,
       -0.74535538,  0.59044576, -0.71079697,  0.39312999, -0.01177649,
        0.25604369, -0.01714393,  0.08088308,  0.55627378, -0.13794   ,
        1.24201741, -0.18035671,  0.85582009, -0.82375446, -0.03666674,
        0.63289625,  0.00478881, -2.03273453, -0.8174242 ,  1.05211306])

In [88]:
aykırı_degerler = [5,22] 

In [89]:
aykırı_degerler_np = np.array(aykırı_degerler)

In [90]:
## satır boyunca birleştirme yapıldı
## concatenate komutu ile de birleştirme yapılabilir.
# aykırı değer bulunduran veri kümesi
aykiri = np.hstack((veri,aykırı_degerler_np))

In [91]:
aykiri

array([-0.48798267, -0.92446845,  1.23405567, -1.54989612,  0.75656341,
       -0.9276027 ,  0.09951093, -1.49163437, -1.02681441,  0.37626649,
        0.58150276,  0.69295655,  1.16071451,  1.49708435,  0.53158002,
        0.48460114,  0.60246452,  0.35324697, -1.10584112, -1.26112983,
        1.97168397, -0.14732788, -0.2540527 , -0.65287303, -0.12305492,
       -0.95918538, -1.89764672, -0.30540646, -0.09437338, -0.54508775,
        5.        , 22.        ])

**Orijinal ve Aykırı Veri Kümelerinde Ortalama ve Medyan Hesabı**

In [94]:
veri_ortanca = np.median(veri)
aykiri_ortanca = np.median(aykiri)
kolon4 = (veri_ortanca,aykiri_ortanca)

In [164]:
veri_ortalama = veri.mean()
aykiri_ortalama = aykiri.mean()
kolon3 = (veri_ortalama,aykiri_ortalama)

In [166]:
## Verinin orijinal halinin ortanca ve ortalaması hesaplanmıştır.
## Ardından aykırı değer eklenmiş halinin ortanca ve ortalaması hesaplanmıştır.
## Buradan aykırı değerlerin ortancayı ortalamaya göre çok daha az etkilediği yorumu yapılabilir.
veri_df2 = pd.DataFrame(kolon3, columns=["Ortalama"], index=["Orijinal","Aykırı"])
veri_df2["Medyan"]= kolon4
veri_df2

Ortalama    Medyan
Orijinal  0.038085 -0.135191
Aykırı    0.737120 -0.108714

**Kesilmiş Ortalama Hesabı**

In [183]:
## Kesilmiş ortalama hesabı:
veri_kesilmis_ortalama1 = stats.tmean(veri)
kolon5 = (veri_kesilmis_ortalama1)

In [182]:
aykiri_kesilmis_ortalama1 = stats.tmean(aykiri)
kolon6= (aykiri_kesilmis_ortalama1)

In [184]:
veri_df3 = pd.DataFrame(kolon5, columns=["Kesilmiş Ortalama Orijinal Veri"], index=[0])
veri_df3["Kesilmiş Ortalama Aykırı Veri"] = kolon6
veri_df3

Kesilmiş Ortalama Orijinal Veri  Kesilmiş Ortalama Aykırı Veri
0                         0.038085                        0.73712

**Her İki Kuyruktan Dağılım Kesilmesi- Trimmed**

In [167]:
## Aşağıda hem orijinal veri kümesine hem de aykırı değer eklenen veri kümesine kesilmiş ortalama tahmin edicisi uygulanmıştır.
# Trimmed
trimmen_orijinal1 = stats.trim_mean(veri, 0.05)
trimmen_orijinal2 = stats.trim_mean(veri, 0.1)
trimmen_orijinal3 = stats.trim_mean(veri, 0.2)
trimmen_orijinal4 = stats.trim_mean(veri, 0.25)

In [168]:
trimmen_aykiri1 = stats.trim_mean(aykiri, 0.05)
trimmen_aykiri2 = stats.trim_mean(aykiri, 0.1)
trimmen_aykiri3 = stats.trim_mean(aykiri, 0.2)
trimmen_aykiri4 = stats.trim_mean(aykiri,0.25)

In [186]:
kolon1 = (trimmen_orijinal1,trimmen_orijinal2,trimmen_orijinal3, trimmen_orijinal4)
kolon2 = (trimmen_aykiri1,trimmen_aykiri2,trimmen_aykiri3, trimmen_aykiri4)
veri_df = pd.DataFrame(kolon1, columns=["Trimmed_Orijinal"], index=[0.05,0.1,0.2,0.25])
veri_df["Trimmed_Aykiri"] = kolon2

In [187]:
veri_df

Trimmed_Orijinal  Trimmed_Aykiri
0.05          0.058673        0.116183
0.10          0.098018       -0.017102
0.20          0.093972       -0.047136
0.25          0.112748       -0.031591

**Broadened Medyan-BMED**

In [105]:
## B-med
# n >= 13 ve n-çift
## median = -0.10

In [107]:
aykiri.sort()

In [108]:
aykiri

array([-1.89764672, -1.54989612, -1.49163437, -1.26112983, -1.10584112,
       -1.02681441, -0.95918538, -0.9276027 , -0.92446845, -0.65287303,
       -0.54508775, -0.48798267, -0.30540646, -0.2540527 , -0.14732788,
       -0.12305492, -0.09437338,  0.09951093,  0.35324697,  0.37626649,
        0.48460114,  0.53158002,  0.58150276,  0.60246452,  0.69295655,
        0.75656341,  1.16071451,  1.23405567,  1.49708435,  1.97168397,
        5.        , 22.        ])

In [124]:
bmed= ((1/10) * (-0.254)) + (1/5*(-0.147 -0.123 -0.094 -0.099)) + ((1/10) * (0.353))

In [125]:
bmed

-0.08270000000000001

In [120]:
## diğer yol:
0.5 - (2.5/30)

0.4166666666666667

In [121]:
## %41.6
# n. 0.416= 
30*0.416 
# 12.47

12.479999999999999

**Verilerin Medyan Mutlak Sapması**

In [156]:
veri_medyan_sapma= stats.median_absolute_deviation(veri)
aykiri_medyan_sapma = stats.median_absolute_deviation(aykiri)
kolon7 = (veri_medyan_sapma)
kolon8 = (aykiri_medyan_sapma)


In [160]:
veri_df4 = pd.DataFrame(kolon7, columns=["Orijinal_Veri_Medyan_Sapma"], index=[0])
veri_df4["Aykiri_Veri_Medyan_Sapma"] = kolon8

In [161]:
veri_df4

Orijinal_Veri_Medyan_Sapma  Aykiri_Veri_Medyan_Sapma
0                    1.131915                  1.198997